# Dependencies
markdown:         kramdown

# Setup
title:            David Ginanni
tagline:          'Full Stack Developer'
description:      'Code for work and viceversa'
url:              https://github.com/GGGGino
baseurl: "/"
url: "" 

works:
  - title: 'Splittami'
    link: 'https://ggggino.github.io/splittami'
    image: '/assets/images/splittami.png'

author:
  name:           'David Ginanni'
  github:         https://github.com/GGGGino
  facebook:       https://www.facebook.com/gino1111
  twitter:        https://twitter.com/GGGGino
  linkedin:       https://www.linkedin.com/in/david-ginanni-4299985a/